In [10]:
from itscalledsoccer.client import AmericanSoccerAnalysis
from plotnine import *
from colour import Color
import numpy as np
import pandas as pd

import numpy as np
from collections import defaultdict

import matplotlib.pyplot as plt

asa_client = AmericanSoccerAnalysis()
from sophso import decorate_team_ids, nwsl_primary_colors, decorate_player_ids

In [2]:
help(asa_client.get_player_xgoals)

Help on method get_player_xgoals in module itscalledsoccer.client:

get_player_xgoals(leagues: Union[str, List[str]] = ['nwsl', 'mls', 'uslc', 'usl1', 'usls', 'nasl', 'mlsnp'], **kwargs) -> pandas.core.frame.DataFrame method of itscalledsoccer.client.AmericanSoccerAnalysis instance
    Retrieves a DataFrame containing player xG data meeting the specified conditions.

    Args:
        leagues (Union[str, List[str]], optional): League(s) on which to filter. Accepts a string or list of strings.

    Keyword Args:
        minimum_minutes (int): Minimum threshold for sum of minutes played.
        minimum_shots (int): Minimum threshold for sum of shots.
        minimum_key_passes (int): Minimum threshold for sum of key passes.
        player_ids (Union[str, List[str]]): Player IDs on which to filter. Cannot be combined with player_names. Accepts a string or list of strings.
        player_names (Union[str, List[str]]): Player names on which to filter. Partial matches are accepted. Cannot be combined with player_ids. Accepts a string or list of strings.
        team_ids (Union[str, List[str]]): Team IDs on which to filter. Cannot be combined with team_names. Accepts a string or list of strings.
        team_names (Union[str, List[str]]): Team names on which to filter. Partial matches and abbreviations are accepted. Cannot be combined with team_ids. Accepts a string or list of strings.
        season_name (Union[str, List[str]]): Name(s)/year(s) of seasons. Cannot be combined with a date range. Accepts a string or list of strings.
        start_date (str): Start of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        end_date (str): End of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        shot_pattern (Union[str, List[str]]): Describes the possessing actions leading to the shot. Valid keywords include: 'Set piece', 'Corner', 'Free kick', 'Penalty', 'Fastbreak', and 'Regular'. Accepts a string or list of strings.
        split_by_teams (bool): Logical indicator to group results by team.
        split_by_seasons (bool): Logical indicator to group results by season.
        split_by_games (bool): Logical indicator to group results by game.
        stage_name (Union[str, List[str]]): Describes the stage of competition in which a game took place. Accepts a string or list of strings.
        general_position (Union[str, List[str]]): Describes the most common position played by each player over the specified period of time. Valid keywords include: 'GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'W', and 'ST'. Accepts a string or list of strings.

    Returns:
        DataFrame

In [11]:
player_xg_df = decorate_team_ids(
    decorate_player_ids(asa_client.get_player_xgoals(leagues="nwsl"))
)

TypeError: unhashable type: 'list'

In [4]:
player_xg_df

,player_id,team_id,general_position,minutes_played,shots,shots_on_target,goals,xgoals,xplace,goals_minus_xgoals,key_passes,primary_assists,xassists,primary_assists_minus_xassists,goals_plus_primary_assists,xgoals_plus_xassists,points_added,xpoints_added
0,0Oq6243Pq6,aDQ0lzvQEv,ST,1278,26,8,3,2.3573,-0.2938,0.6427,15,3,1.1161,1.8839,6,3.4734,1.7547,1.1915
1,0Oq62D2xq6,4wM4rZdqjB,CM,69,4,0,0,0.8177,-0.8177,-0.8177,2,0,0.1859,-0.1859,0,1.0036,0.0000,0.7659
2,0Oq62ob2q6,4JMAk47qKg,GK,105,0,0,0,0.0000,0.0000,0.0000,0,0,0.0000,0.0000,0,0.0000,0.0000,0.0000
3,0Oq632XPQ6,aDQ0lzvQEv,FB,253,4,0,0,0.2499,-0.2499,-0.2499,2,0,0.0510,-0.0510,0,0.3009,0.0000,0.2827
4,0Oq63DazQ6,raMyrr25d2,FB,1000,6,3,1,0.4487,0.2138,0.5513,8,1,0.4433,0.5567,2,0.8920,0.0197,0.1120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,zeQZJXGZQK,"[Pk5LeeNqOW, kRQaWa15KZ, eV5D2w9QKn]",CB,13906,42,13,4,2.4549,0.2224,1.5451,33,3,2.2515,0.7485,7,4.7064,1.0620,1.4749
866,zeQZJXnKQK,"[4wM4rZdqjB, kRQa8JOqKZ]",GK,1243,0,0,0,0.0000,0.0000,0.0000,1,0,0.0944,-0.0944,0,0.0944,0.0000,0.0000
867,zeQZJXvKQK,7vQ7BBzqD1,DM,2490,38,20,6,5.8703,-0.1738,0.1297,44,3,2.9597,0.0403,9,8.8300,4.2047,4.0131
868,zeQZXA7r5K,eV5DR6YQKn,CM,3428,63,23,4,5.5737,1.2353,-1.5737,33,3,1.6136,1.3864,7,7.1873,2.7283,3.5407
869,zeQZXkwD5K,KPqjw8PQ6v,DM,1988,14,4,1,0.9662,0.1669,0.0338,16,0,1.4282,-1.4282,1,2.3945,0.8207,0.9671

In [6]:
player_xg_df["xg_diff"] = player_xg_df.goals - player_xg_df.xgoals

In [9]:
player_xg_df.sort_values("goals_minus_xgoals")

,player_id,team_id,general_position,minutes_played,shots,shots_on_target,goals,xgoals,xplace,goals_minus_xgoals,key_passes,primary_assists,xassists,primary_assists_minus_xassists,goals_plus_primary_assists,xgoals_plus_xassists,points_added,xpoints_added,xg_diff
225,9Yqdog7k5v,"[kRQa8JOqKZ, Pk5LeeNqOW]",ST,4038,140,53,11,19.6694,-2.9803,-8.6694,33,3,3.3535,-0.3535,14,23.0228,7.8008,13.0290,-8.6694
688,OlMl9V9D5L,"[xW5pwDBMg1, raMyrr25d2, 4wM4rZdqjB, 7vQ7BBzqD...",ST,15611,726,283,77,85.2441,-3.9436,-8.2441,234,30,27.0634,2.9366,107,112.3075,25.8953,43.1061,-8.2441
78,2lqRkmXAQr,"[KPqjw8PQ6v, eV5DR6YQKn]",FB,16805,124,31,3,9.8384,-3.7203,-6.8384,101,14,11.3215,2.6785,17,21.1599,1.6734,6.2090,-6.8384
513,KPqj7omEQ6,"[4JMAk47qKg, 4wM4rZdqjB]",W,9427,202,84,16,22.7153,-1.9869,-6.7153,122,14,15.4249,-1.4249,30,38.1402,4.8786,12.5557,-6.7153
38,0x5g2EoZM7,"[kRQa8JOqKZ, 7VqG1lYMvW, KPqjw8PQ6v, 7vQ7BBzqD...",ST,7292,171,66,15,21.5116,0.2679,-6.5116,102,12,9.5956,2.4044,27,31.1071,7.3534,14.5500,-6.5116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,N6Mm7odPqE,7vQ7BBzqD1,W,7330,316,124,37,29.9411,3.7307,7.0589,212,20,21.5477,-1.5477,57,51.4888,16.1982,17.7078,7.0589
87,2lqRRddLqr,"[4wM4rZdqjB, zeQZeazqKw]",AM,15430,524,187,72,64.0234,0.3634,7.9766,316,25,38.4963,-13.4963,97,102.5197,19.7610,26.6975,7.9766
135,4JMAak3kMK,XVqKeVKM01,W,12519,332,123,45,36.9347,3.5235,8.0653,272,19,24.5264,-5.5264,64,61.4612,21.5373,19.4825,8.0653
86,2lqRR7knqr,"[KPqjw8PQ6v, raMyrr25d2]",ST,6909,346,170,57,43.9909,7.4122,13.0091,114,12,11.8702,0.1298,69,55.8611,26.5205,25.0408,13.0091
666,odMX8EJoMY,Pk5LeeNqOW,ST,14803,360,149,60,45.9328,5.8319,14.0672,229,12,21.5352,-9.5352,72,67.4681,21.3898,24.1839,14.0672