In [1]:
from itscalledsoccer.client import AmericanSoccerAnalysis
from plotnine import *
from colour import Color
import numpy as np
import pandas as pd

import numpy as np
from collections import defaultdict

import matplotlib.pyplot as plt

asa_client = AmericanSoccerAnalysis()

In [2]:
from sophso import (
    decorate_team_ids,
    nwsl_primary_colors,
    geom_image,
    decorate_player_ids,
)

In [3]:
help(asa_client.get_player_goals_added)

Help on method get_player_goals_added in module itscalledsoccer.client:

get_player_goals_added(leagues: Union[str, List[str]] = ['nwsl', 'mls', 'uslc', 'usl1', 'usls', 'nasl', 'mlsnp'], **kwargs) -> pandas.core.frame.DataFrame method of itscalledsoccer.client.AmericanSoccerAnalysis instance
    Retrieves a DataFrame containing player g+ data meeting the specified conditions.

    Args:
        leagues (Union[str, List[str]], optional): League(s) on which to filter. Accepts a string or list of strings. Defaults to LEAGUES.

    Keyword Args:
        minimum_minutes (int): Minimum threshold for sum of minutes played.
        player_ids (Union[str, List[str]]): Player IDs on which to filter. Cannot be combined with player_names. Accepts a string or list of strings.
        player_names (Union[str, List[str]]): Player names on which to filter. Partial matches are accepted. Cannot be combined with player_ids. Accepts a string or list of strings.
        team_ids (Union[str, List[str]]): Team IDs on which to filter. Cannot be combined with team_names. Accepts a string or list of strings.
        team_names (Union[str, List[str]]): Team names on which to filter. Partial matches and abbreviations are accepted. Cannot be combined with team_ids. Accepts a string or list of strings.
        season_name (Union[str, List[str]]): Name(s)/year(s) of seasons. Cannot be combined with a date range. Accepts a string or list of strings.
        start_date (str): Start of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        end_date (str): End of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        split_by_teams (bool): Logical indicator to group results by team.
        split_by_seasons (bool): Logical indicator to group results by season.
        split_by_games (bool): Logical indicator to group results by game.
        stage_name (Union[str, List[str]]): Describes the stage of competition in which a game took place. Accepts a string or list of strings.
        action_type (Union[str, List[str]]): Describes the goals added (g+) action type. Valid keywords include: 'Dribbling', 'Fouling', 'Interrupting', 'Passing', 'Receiving', and 'Shooting'. Accepts a string or list of strings.
        general_position (Union[str, List[str]]): Describes the most common position played by each player over the specified period of time. Valid keywords include: 'GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'W', and 'ST'. Accepts a string or list of strings.
        above_replacement (bool): Logical indicator to compare players against replacement-level values. This will only return aggregated g+ values, rather than disaggregated g+ values by action type.

    Returns:
        DataFrame

In [4]:
gplus_df = decorate_player_ids(
    decorate_team_ids(
        asa_client.get_player_goals_added(
            leagues="nwsl",
            season_name="2025",
            team_ids="eV5DR6YQKn",
            split_by_games=True,
        )
    )
)

In [5]:
gplus_df

,player_id,game_id,team_id,general_position,minutes_played,data,team,team_logo,player,player_headshot
0,0Oq6wZexQ6,2lqRpdZ0Mr,eV5DR6YQKn,W,110,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....
1,0Oq6wZexQ6,4wM4bRykqj,eV5DR6YQKn,W,70,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....
2,0Oq6wZexQ6,7vQ7bja2qD,eV5DR6YQKn,W,95,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....
3,0Oq6wZexQ6,9vQ2bnVYQK,eV5DR6YQKn,W,88,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....
4,0Oq6wZexQ6,9z5kjk9jMA,eV5DR6YQKn,W,99,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....
...,...,...,...,...,...,...,...,...,...,...
138,zeQZXA7r5K,9vQ2bnVYQK,eV5DR6YQKn,CM,59,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....
139,zeQZXA7r5K,jYQJmLDBqG,eV5DR6YQKn,CM,36,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....
140,zeQZXA7r5K,jYQJmLDPqG,eV5DR6YQKn,DM,105,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....
141,zeQZXA7r5K,NWMWp4Ej5l,eV5DR6YQKn,CM,102,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....
142,zeQZXA7r5K,p6qbjWeBq0,eV5DR6YQKn,ST,8,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....

In [6]:
gplus_df.iloc[0].data

[{'action_type': 'Dribbling',
  'goals_added_raw': 0.014100000000000001,
  'goals_added_above_avg': -0.013000000000000001,
  'count_actions': 15},
 {'action_type': 'Fouling',
  'goals_added_raw': 0.0017000000000000001,
  'goals_added_above_avg': -0.0057,
  'count_actions': 3},
 {'action_type': 'Interrupting',
  'goals_added_raw': 0.0344,
  'goals_added_above_avg': -0.0158,
  'count_actions': 21},
 {'action_type': 'Passing',
  'goals_added_raw': 0.06810000000000001,
  'goals_added_above_avg': 0.08030000000000001,
  'count_actions': 33},
 {'action_type': 'Receiving',
  'goals_added_raw': 0.1013,
  'goals_added_above_avg': -0.0286,
  'count_actions': 29},
 {'action_type': 'Shooting',
  'goals_added_raw': 0.030500000000000003,
  'goals_added_above_avg': -0.0298,
  'count_actions': 1}]

In [7]:
help(asa_client.get_player_goals_added)

Help on method get_player_goals_added in module itscalledsoccer.client:

get_player_goals_added(leagues: Union[str, List[str]] = ['nwsl', 'mls', 'uslc', 'usl1', 'usls', 'nasl', 'mlsnp'], **kwargs) -> pandas.core.frame.DataFrame method of itscalledsoccer.client.AmericanSoccerAnalysis instance
    Retrieves a DataFrame containing player g+ data meeting the specified conditions.

    Args:
        leagues (Union[str, List[str]], optional): League(s) on which to filter. Accepts a string or list of strings. Defaults to LEAGUES.

    Keyword Args:
        minimum_minutes (int): Minimum threshold for sum of minutes played.
        player_ids (Union[str, List[str]]): Player IDs on which to filter. Cannot be combined with player_names. Accepts a string or list of strings.
        player_names (Union[str, List[str]]): Player names on which to filter. Partial matches are accepted. Cannot be combined with player_ids. Accepts a string or list of strings.
        team_ids (Union[str, List[str]]): Team IDs on which to filter. Cannot be combined with team_names. Accepts a string or list of strings.
        team_names (Union[str, List[str]]): Team names on which to filter. Partial matches and abbreviations are accepted. Cannot be combined with team_ids. Accepts a string or list of strings.
        season_name (Union[str, List[str]]): Name(s)/year(s) of seasons. Cannot be combined with a date range. Accepts a string or list of strings.
        start_date (str): Start of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        end_date (str): End of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        split_by_teams (bool): Logical indicator to group results by team.
        split_by_seasons (bool): Logical indicator to group results by season.
        split_by_games (bool): Logical indicator to group results by game.
        stage_name (Union[str, List[str]]): Describes the stage of competition in which a game took place. Accepts a string or list of strings.
        action_type (Union[str, List[str]]): Describes the goals added (g+) action type. Valid keywords include: 'Dribbling', 'Fouling', 'Interrupting', 'Passing', 'Receiving', and 'Shooting'. Accepts a string or list of strings.
        general_position (Union[str, List[str]]): Describes the most common position played by each player over the specified period of time. Valid keywords include: 'GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'W', and 'ST'. Accepts a string or list of strings.
        above_replacement (bool): Logical indicator to compare players against replacement-level values. This will only return aggregated g+ values, rather than disaggregated g+ values by action type.

    Returns:
        DataFrame

In [8]:
gplus_df = decorate_player_ids(
    decorate_team_ids(
        asa_client.get_player_goals_added(
            leagues="nwsl",
            season_name="2025",
            team_ids="eV5DR6YQKn",
            above_replacement=True,
            # split_by_games=True,
        )
    )
)

In [9]:
gplus_df["gplus_p96"] = (
    96 * gplus_df["goals_added_above_replacement"] / gplus_df["minutes_played"]
)

gplus_df.sort_values("gplus_p96", ascending=False)

,player_id,team_id,general_position,minutes_played,goals_added_raw,goals_added_above_replacement,count_actions,team,team_logo,player,player_headshot,gplus_p96
11,odMXGw2oQY,eV5DR6YQKn,ST,828,2.5322,2.0379,588,LOU,https://american-soccer-analysis-headshots.s3....,Kayla Fischer,https://american-soccer-analysis-headshots.s3....,0.236278
8,KPqjKkoPQ6,eV5DR6YQKn,CM,766,1.5194,1.3837,688,LOU,https://american-soccer-analysis-headshots.s3....,Savannah DeMelo,https://american-soccer-analysis-headshots.s3....,0.173414
7,KPqjBzzRq6,eV5DR6YQKn,W,1070,2.2245,1.7569,732,LOU,https://american-soccer-analysis-headshots.s3....,Emma Sears,https://american-soccer-analysis-headshots.s3....,0.157628
4,a35rnK125L,eV5DR6YQKn,ST,533,1.1399,0.8743,267,LOU,https://american-soccer-analysis-headshots.s3....,Sarah Weber,https://american-soccer-analysis-headshots.s3....,0.157472
6,KAqBRVn7qb,eV5DR6YQKn,CM,648,1.1721,1.0604,396,LOU,https://american-soccer-analysis-headshots.s3....,Katie O'Kane,https://american-soccer-analysis-headshots.s3....,0.157096
13,Vj583B8LM8,eV5DR6YQKn,FB,488,0.8582,0.6617,370,LOU,https://american-soccer-analysis-headshots.s3....,Ella Hase,https://american-soccer-analysis-headshots.s3....,0.130170
0,0Oq6wZexQ6,eV5DR6YQKn,W,799,1.3988,1.0497,632,LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,0.126122
1,2lqRk0vaQr,eV5DR6YQKn,DM,1010,1.2905,1.2063,866,LOU,https://american-soccer-analysis-headshots.s3....,Taylor Flint,https://american-soccer-analysis-headshots.s3....,0.114658
15,zeQZXA7r5K,eV5DR6YQKn,CM,490,0.6182,0.5222,375,LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....,0.102309
14,wvq9gol1MW,eV5DR6YQKn,CB,818,1.0563,0.8467,487,LOU,https://american-soccer-analysis-headshots.s3....,Ellie Jean,https://american-soccer-analysis-headshots.s3....,0.099368
9,KPqjKzG2Q6,eV5DR6YQKn,FB,1128,1.4837,1.0526,883,LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.089583
5,eV5Dzp7nQK,eV5DR6YQKn,CM,428,0.4037,0.3419,307,LOU,https://american-soccer-analysis-headshots.s3....,Marisa DiGrande,https://american-soccer-analysis-headshots.s3....,0.076688
2,2lqRkmXAQr,eV5DR6YQKn,CB,1128,1.0965,0.8075,824,LOU,https://american-soccer-analysis-headshots.s3....,Arin Wright,https://american-soccer-analysis-headshots.s3....,0.068723
12,odMXRl80qY,eV5DR6YQKn,W,72,0.0700,0.0449,65,LOU,https://american-soccer-analysis-headshots.s3....,Uchenna Kanu,https://american-soccer-analysis-headshots.s3....,0.059867
10,NWMWV0NYQl,eV5DR6YQKn,FB,1027,0.9087,0.5515,780,LOU,https://american-soccer-analysis-headshots.s3....,Courtney Petersen,https://american-soccer-analysis-headshots.s3....,0.051552
3,2lqRkN10Qr,eV5DR6YQKn,CM,14,-0.0006,-0.0028,7,LOU,https://american-soccer-analysis-headshots.s3....,Elli Pikkujamsa,https://american-soccer-analysis-headshots.s3....,-0.019200

In [10]:
def explode_actions(action_list):
    row_dict = {}
    for action in action_list:
        action_type = action["action_type"]
        for action_value in [
            "goals_added_raw",
            # "goals_added_above_avg",
            # "count_actions",
        ]:
            row_dict[f"{action_type} {action_value}"] = action[action_value]

    return row_dict


gplus_df = decorate_player_ids(
    decorate_team_ids(
        asa_client.get_player_goals_added(
            leagues="nwsl",
            season_name="2025",
            team_ids="eV5DR6YQKn",
            # split_by_games=True,
        )
    )
)

gplus_df = pd.concat(
    [gplus_df, pd.DataFrame(gplus_df.data.apply(explode_actions).to_list())], axis=1
)

In [11]:
gplus_df.loc[:, gplus_df.columns[gplus_df.columns.str.contains("goals_added_raw")]].sum(
    axis=1
)

0     1.3989
1     1.2906
2     1.0965
3    -0.0007
4     1.1400
5     0.4037
6     1.1721
7     2.2245
8     1.5194
9     1.4836
10    0.9088
11    2.5323
12    0.0700
13    0.8582
14    1.0563
15    0.6182
dtype: float64

In [12]:
gplus_df["goals_added_raw_total"] = gplus_df.loc[
    :, gplus_df.columns[gplus_df.columns.str.contains("goals_added_raw")]
].sum(axis=1)

In [13]:
gplus_df["goals_added_raw_p96"] = (
    96 * gplus_df["goals_added_raw_total"] / gplus_df["minutes_played"]
)

In [14]:
gplus_df.sort_values("goals_added_raw_p96", ascending=False)

,player_id,team_id,general_position,minutes_played,data,team,team_logo,player,player_headshot,Dribbling goals_added_raw,Fouling goals_added_raw,Interrupting goals_added_raw,Passing goals_added_raw,Receiving goals_added_raw,Shooting goals_added_raw,goals_added_raw_total,goals_added_raw_p96
11,odMXGw2oQY,eV5DR6YQKn,ST,828,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Kayla Fischer,https://american-soccer-analysis-headshots.s3....,-0.1099,-0.1377,0.7401,-0.1042,1.5573,0.5867,2.5323,0.293600
4,a35rnK125L,eV5DR6YQKn,ST,533,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Sarah Weber,https://american-soccer-analysis-headshots.s3....,0.3277,0.0264,0.1546,-0.3832,0.7717,0.2428,1.1400,0.205328
7,KPqjBzzRq6,eV5DR6YQKn,W,1070,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Emma Sears,https://american-soccer-analysis-headshots.s3....,0.4620,-0.2567,0.4639,-0.4929,1.2297,0.8185,2.2245,0.199581
8,KPqjKkoPQ6,eV5DR6YQKn,CM,766,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Savannah DeMelo,https://american-soccer-analysis-headshots.s3....,0.0709,0.0984,0.0376,0.0691,0.6531,0.5903,1.5194,0.190421
6,KAqBRVn7qb,eV5DR6YQKn,CM,648,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Katie O'Kane,https://american-soccer-analysis-headshots.s3....,-0.0075,0.2548,0.3022,0.3170,0.1758,0.1298,1.1721,0.173644
13,Vj583B8LM8,eV5DR6YQKn,FB,488,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ella Hase,https://american-soccer-analysis-headshots.s3....,-0.0075,0.0208,0.6061,0.0826,0.1562,0.0000,0.8582,0.168826
0,0Oq6wZexQ6,eV5DR6YQKn,W,799,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0618,0.2459,0.3275,0.0962,0.6389,0.1522,1.3989,0.168078
9,KPqjKzG2Q6,eV5DR6YQKn,FB,1128,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.1524,-0.0633,0.5199,0.6865,0.1010,0.0871,1.4836,0.126264
14,wvq9gol1MW,eV5DR6YQKn,CB,818,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ellie Jean,https://american-soccer-analysis-headshots.s3....,-0.0490,0.0050,0.5650,0.1471,0.3376,0.0506,1.0563,0.123967
1,2lqRk0vaQr,eV5DR6YQKn,DM,1010,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Taylor Flint,https://american-soccer-analysis-headshots.s3....,-0.0376,-0.2431,0.6814,0.1351,0.4308,0.3240,1.2906,0.122671
15,zeQZXA7r5K,eV5DR6YQKn,CM,490,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Ary Borges,https://american-soccer-analysis-headshots.s3....,-0.0705,-0.0586,0.2040,-0.0352,0.4032,0.1753,0.6182,0.121117
12,odMXRl80qY,eV5DR6YQKn,W,72,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Uchenna Kanu,https://american-soccer-analysis-headshots.s3....,-0.1154,0.0310,-0.0588,0.0022,0.1500,0.0610,0.0700,0.093333
2,2lqRkmXAQr,eV5DR6YQKn,CB,1128,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Arin Wright,https://american-soccer-analysis-headshots.s3....,-0.0430,0.0011,0.4928,0.4709,0.0848,0.0899,1.0965,0.093319
5,eV5Dzp7nQK,eV5DR6YQKn,CM,428,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Marisa DiGrande,https://american-soccer-analysis-headshots.s3....,-0.0430,0.0195,0.3284,-0.0398,0.0491,0.0895,0.4037,0.090550
10,NWMWV0NYQl,eV5DR6YQKn,FB,1027,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Courtney Petersen,https://american-soccer-analysis-headshots.s3....,0.0140,0.0086,0.1421,0.6328,0.0088,0.1025,0.9088,0.084951
3,2lqRkN10Qr,eV5DR6YQKn,CM,14,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Elli Pikkujamsa,https://american-soccer-analysis-headshots.s3....,0.0034,0.0000,0.0000,-0.0040,-0.0001,0.0000,-0.0007,-0.004800

In [15]:
asa_client.get_games(game_ids=list(gplus_df.game_id.unique()))

AttributeError: 'DataFrame' object has no attribute 'game_id'

In [ ]:
gplus_df.game_id.unique()

array(['2lqRpdZ0Mr', '4wM4bRykqj', '7vQ7bja2qD', '9vQ2bnVYQK',
       '9z5kjk9jMA', 'BLMvj2lOMx', 'jYQJmLDBqG', 'jYQJmLDPqG',
       'KXMeZ6er56', 'NWMWp4Ej5l'], dtype=object)

In [ ]:
gplus_df.query("player == 'Lauren Milliet'")

,player_id,game_id,team_id,general_position,minutes_played,data,team,team_logo,player,player_headshot,Dribbling goals_added_raw,Fouling goals_added_raw,Interrupting goals_added_raw,Passing goals_added_raw,Receiving goals_added_raw,Shooting goals_added_raw,goals_added_raw_total
76,KPqjKzG2Q6,2lqRpdZ0Mr,eV5DR6YQKn,FB,110,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0091,-0.0025,0.0211,0.1344,0.0062,0.000000,0.168300
77,KPqjKzG2Q6,4wM4bRykqj,eV5DR6YQKn,FB,107,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0256,0.0000,0.0315,0.0393,0.0200,0.000000,0.116400
78,KPqjKzG2Q6,7vQ7bja2qD,eV5DR6YQKn,FB,104,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,-0.0313,-0.0740,0.0386,0.0354,0.0054,0.000000,-0.025900
79,KPqjKzG2Q6,9vQ2bnVYQK,eV5DR6YQKn,FB,97,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,-0.0038,0.0037,-0.0096,0.0526,-0.0057,0.000000,0.037200
80,KPqjKzG2Q6,9z5kjk9jMA,eV5DR6YQKn,FB,99,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,-0.0132,0.0000,0.1070,0.0550,0.0020,0.000000,0.150800
81,KPqjKzG2Q6,BLMvj2lOMx,eV5DR6YQKn,FB,104,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0272,0.0000,0.1929,0.0338,0.0071,0.024200,0.285200
82,KPqjKzG2Q6,jYQJmLDBqG,eV5DR6YQKn,FB,101,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,-0.0003,0.0017,0.0265,-0.0114,0.0078,0.035100,0.059400
83,KPqjKzG2Q6,jYQJmLDPqG,eV5DR6YQKn,FB,105,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0369,0.0021,0.0364,0.0474,0.0073,0.000005,0.130105
84,KPqjKzG2Q6,KXMeZ6er56,eV5DR6YQKn,FB,101,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0474,0.0057,0.0658,0.0968,0.0054,0.000000,0.221100
85,KPqjKzG2Q6,NWMWp4Ej5l,eV5DR6YQKn,FB,102,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Lauren Milliet,https://american-soccer-analysis-headshots.s3....,0.0298,0.0000,-0.0027,0.0687,0.0206,0.000000,0.116400

In [ ]:
gplus_df.query("player == 'Janine Sonis'")

,player_id,game_id,team_id,general_position,minutes_played,data,team,team_logo,player,player_headshot,Dribbling goals_added_raw,Fouling goals_added_raw,Interrupting goals_added_raw,Passing goals_added_raw,Receiving goals_added_raw,Shooting goals_added_raw,goals_added_raw_total
0,0Oq6wZexQ6,2lqRpdZ0Mr,eV5DR6YQKn,W,110,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,0.0141,0.0017,0.0344,0.0681,0.1013,0.0305,0.2501
1,0Oq6wZexQ6,4wM4bRykqj,eV5DR6YQKn,W,70,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0414,0.0000,0.0574,-0.0281,0.0521,0.0000,0.0400
2,0Oq6wZexQ6,7vQ7bja2qD,eV5DR6YQKn,W,95,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0055,-0.0174,0.0843,-0.0075,0.0848,0.0377,0.1764
3,0Oq6wZexQ6,9vQ2bnVYQK,eV5DR6YQKn,W,88,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,0.0174,0.0000,0.0219,-0.0562,0.0422,0.0286,0.0539
4,0Oq6wZexQ6,9z5kjk9jMA,eV5DR6YQKn,W,99,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,0.0167,-0.0023,0.0234,-0.0093,0.1143,0.0112,0.1540
5,0Oq6wZexQ6,BLMvj2lOMx,eV5DR6YQKn,W,104,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0095,0.2510,0.0716,0.0836,0.0352,0.0000,0.4319
6,0Oq6wZexQ6,jYQJmLDBqG,eV5DR6YQKn,W,31,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,0.0054,0.0000,0.0029,-0.0073,0.0318,0.0000,0.0328
7,0Oq6wZexQ6,jYQJmLDPqG,eV5DR6YQKn,W,40,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0206,0.0000,0.0006,-0.0168,0.0038,0.0100,-0.0230
8,0Oq6wZexQ6,KXMeZ6er56,eV5DR6YQKn,W,63,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0606,-0.0044,-0.0014,0.0244,0.1142,0.0338,0.1060
9,0Oq6wZexQ6,NWMWp4Ej5l,eV5DR6YQKn,W,32,"[{'action_type': 'Dribbling', 'goals_added_raw...",LOU,https://american-soccer-analysis-headshots.s3....,Janine Sonis,https://american-soccer-analysis-headshots.s3....,-0.0114,0.0173,0.0126,0.0137,0.0198,0.0000,0.0520

In [ ]:
help(asa_client.get_player_xpass)

Help on method get_player_xpass in module itscalledsoccer.client:

get_player_xpass(leagues: Union[str, List[str]] = ['nwsl', 'mls', 'uslc', 'usl1', 'usls', 'nasl', 'mlsnp'], **kwargs) -> pandas.core.frame.DataFrame method of itscalledsoccer.client.AmericanSoccerAnalysis instance
    Retrieves a DataFrame containing player xPass data meeting the specified conditions.

    Args:
        leagues (Union[str, List[str]], optional): League(s) on which to filter. Accepts a string or list of strings. Defaults to LEAGUES.

    Keyword Args:
        minimum_minutes (int): Minimum threshold for sum of minutes played.
        minimum_passes (int): Minimum threshold for sum of attempted passes.
        player_ids (Union[str, List[str]]): Player IDs on which to filter. Cannot be combined with player_names. Accepts a string or list of strings.
        player_names (Union[str, List[str]]): Player names on which to filter. Partial matches are accepted. Cannot be combined with player_ids. Accepts a string or list of strings.
        team_ids (Union[str, List[str]]): Team IDs on which to filter. Cannot be combined with team_names. Accepts a string or list of strings.
        team_names (Union[str, List[str]]): Team names on which to filter. Partial matches and abbreviations are accepted. Cannot be combined with team_ids. Accepts a string or list of strings.
        season_name (Union[str, List[str]]): Name(s)/year(s) of seasons. Cannot be combined with a date range. Accepts a string or list of strings.
        start_date (str): Start of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        end_date (str): End of a date range. Must be a string in YYYY-MM-DD format. Cannot be combined with season_name.
        pass_origin_third (Union[str, List[str]]): Describes the third of the field from which the pass originated. Valid keywords include: 'Attacking', 'Middle', and 'Defensive'. Accepts a string or list of strings.
        split_by_teams (bool): Logical indicator to group results by team.
        split_by_seasons (bool): Logical indicator to group results by season.
        split_by_games (bool): Logical indicator to group results by game.
        stage_name (Union[str, List[str]]): Describes the stage of competition in which a game took place. Accepts a string or list of strings.
        general_position (Union[str, List[str]]): Describes the most common position played by each player over the specified period of time. Valid keywords include: 'GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'W', and 'ST'. Accepts a string or list of strings.

    Returns:
        DataFrame

In [ ]:
asa_client.get_player_xpass(
    leagues="nwsl",
    season_name="2025",
    team_ids="eV5DR6YQKn",
    split_by_games=True,
)

,player_id,game_id,team_id,general_position,minutes_played,attempted_passes,pass_completion_percentage,xpass_completion_percentage,passes_completed_over_expected,passes_completed_over_expected_p100,avg_distance_yds,avg_vertical_distance_yds,share_team_touches
0,0Oq6wZexQ6,2lqRpdZ0Mr,eV5DR6YQKn,W,110,33,0.6667,0.5313,4.4678,13.5389,29.8522,6.9865,0.1322
1,0Oq6wZexQ6,4wM4bRykqj,eV5DR6YQKn,W,70,22,0.3636,0.5572,-4.2584,-19.3566,25.6008,8.2680,0.0745
2,0Oq6wZexQ6,7vQ7bja2qD,eV5DR6YQKn,W,95,15,0.7333,0.6143,1.7849,11.8992,17.4287,4.7202,0.0647
3,0Oq6wZexQ6,9vQ2bnVYQK,eV5DR6YQKn,W,88,26,0.7308,0.7205,0.2673,1.0280,20.5888,2.7815,0.0756
4,0Oq6wZexQ6,9z5kjk9jMA,eV5DR6YQKn,W,99,26,0.5769,0.6331,-1.4598,-5.6147,14.0944,-2.2746,0.0898
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,zeQZXA7r5K,4wM4bRykqj,eV5DR6YQKn,CM,70,20,0.6000,0.6997,-1.9942,-9.9711,18.1317,7.3635,0.0621
135,zeQZXA7r5K,9vQ2bnVYQK,eV5DR6YQKn,CM,59,15,0.8000,0.8209,-0.3140,-2.0934,18.7571,1.7764,0.0583
136,zeQZXA7r5K,jYQJmLDBqG,eV5DR6YQKn,CM,36,8,0.3750,0.5324,-1.2589,-15.7364,14.3972,4.5936,0.0279
137,zeQZXA7r5K,jYQJmLDPqG,eV5DR6YQKn,DM,105,33,0.6970,0.7792,-2.7134,-8.2223,14.6337,0.1006,0.1102
138,zeQZXA7r5K,NWMWp4Ej5l,eV5DR6YQKn,CM,102,27,0.6296,0.6731,-1.1743,-4.3494,14.1606,0.4539,0.1066

In [16]:
team_df = asa_client.get_team_goals_added(
    leagues="nwsl", season="2025", gamestate_trunc=["-1", "0"]
)

In [20]:
team_df.data[0]

[{'action_type': 'Dribbling',
  'num_actions_for': 739,
  'goals_added_for': 0.327,
  'num_actions_against': 887,
  'goals_added_against': 0.846},
 {'action_type': 'Shooting',
  'num_actions_for': 65,
  'goals_added_for': 1.5238,
  'num_actions_against': 75,
  'goals_added_against': 1.9395},
 {'action_type': 'Passing',
  'num_actions_for': 2434,
  'goals_added_for': 0.20650000000000002,
  'num_actions_against': 2659,
  'goals_added_against': 0.3039},
 {'action_type': 'Interrupting',
  'num_actions_for': 560,
  'goals_added_for': 2.6923,
  'num_actions_against': 564,
  'goals_added_against': 2.4331},
 {'action_type': 'Receiving',
  'num_actions_for': 1873,
  'goals_added_for': 2.8018,
  'num_actions_against': 2131,
  'goals_added_against': 3.5444},
 {'action_type': 'Claiming',
  'num_actions_for': 2,
  'goals_added_for': -0.0011,
  'num_actions_against': 9,
  'goals_added_against': -0.06420000000000001},
 {'action_type': 'Fouling',
  'num_actions_for': 61,
  'goals_added_for': 0.2401,
  'num_actions_against': 59,
  'goals_added_against': 0.4572}]

In [18]:
team_df = pd.concat(
    [team_df, pd.DataFrame(team_df.data.apply(explode_actions).to_list())], axis=1
)

KeyError: 'goals_added_raw'

In [ ]:
team_df = asa_client.get_team_goals_added(
    leagues="nwsl", season="2025", gamestate_trunc=["-1", "0"]
)


team_df = decorate_team_ids(team_df)
team_df["xgoal_difference_per_game"] = team_df.xgoal_difference / team_df.count_games

team_df = team_df.sort_values("xgoal_difference_per_game", ascending=False).reset_index(
    drop=True
)

plot = (
    ggplot(
        team_df,
        aes(x="team", y="xgoal_difference_per_game", fill="team"),
    )
    + geom_col()
    + scale_fill_manual(nwsl_primary_colors, guide=None)
    + scale_x_discrete(limits=team_df.team)
    + geom_image(aes(image="team_logo"))
    + labs(
        y="xGD",
        title=f"Average expected goal differential by team, NWSL 2025 season through week {team_df.count_games.min()}",
        caption="""
    xGD here measures expected goals - expected goals allowed by team per game, averaged over the season.
    xGD is adjusted for the share of home games played. 
    Data: American Soccer Analysis""",
    )
)